[database]
fname_tracked_items = 'Tracked _'
fname_movements = 'All movements _'
only_keep_latest_version = true
save_movements = false
reports_path = ''

[input_data]
sku_features = ['Brand', 'Category']
company_features = ['Country']
