[database]
filename_tracked_items = 'Tracked _'
filename_movements = 'All movements _'
filename_files_processed = 'input_files_processed.pkl'
only_keep_latest_version = true
save_movements = false
reports_path = ''